### ISSUE TITLE
GoLand

### ISSUE THREAD

**Issue by spyroot** [Kuniwak/iceberg.icls#2]
Hi,

I've tested icls file with latest goLand build. It does work, but could you also provide a setting file.  I think on the new build you have to export while you disable sync.  Because editor color miss-matches with the rest.

Thank you

**Comment by Kuniwak** [comment]
@spyroot Sorry for my late reply. 

I added setting file at a9451f9.

**Comment by spyroot** [comment]
amazing thank you
